### ISSUE TITLE
Extend this example to include a mysql container

### ISSUE THREAD

**Issue by tripper54** [CircleCI-Public/sample-php-laravel#11]
Hi there,

Thanks for putting this example together, it has been a great help!

It would be really cool if you could extend it to include a mysql container for the DB layer. I think an example that included a second mysql container would cover typical use cases a lot better.

Thanks!

**Comment by ec-wagner** [comment]
Trying to figure out how to use a [circleci MySQL container](https://hub.docker.com/r/circleci/mysql/) with this example. Can someone please push me in the right direction.

this is how my config.yml looks like:

```yaml
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
        environment:
          MYSQL_HOST: 127.0.0.1
          MYSQL_DB: testing
          MYSQL_USER: testing
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_PASSWORD: testing

      - image: mysql:5.7
        environment:
            MYSQL_USER: testing
            MYSQL_ALLOW_EMPTY_PASSWORD: true

    working_directory: ~/laravel

    steps:
      - checkout
      - run: sudo apt install -y libsqlite3-dev zlib1g-dev
      - run: sudo docker-php-ext-install zip
      - run: composer install -n --prefer-dist
      # - run: composer install --dev --ignore-platform-reqs

      # prepare the database
      - run:
          name: Create Mysql Database
          command: mysql  -h 127.0.0.1 -u root -e "create database testing;"
```

the build breaks at last step
```bash
#!/bin/bash -eo pipefail
mysql  -h 127.0.0.1 -u root -e "create database testing;"
/bin/bash: mysql: command not found
Exited with code 127
```
