### ISSUE TITLE
Add example of nightly scheduled build to circleci/config.yml

### ISSUE THREAD

**Issue by limonte** [CircleCI-Public/sample-php-laravel#5]
Hi there!

I'm trying to set up a nightly build for my project and my config looks like this:

```
version: 2

jobs:
  build:
    machine: true

    steps:
      - ...
```

Then I decided to add a nightly scheduled build to it and found https://circleci.com/docs/2.0/workflows/#scheduling-a-workflow

So I added the `nightly` section to the config:

```
version: 2

jobs:
  build:
    machine: true

    steps:
      - ...

nightly:
  triggers:
    - schedule:
        cron: "0 0 * * *"
```

But it doesn't work. 

---

#### I was wondering is it possible add the example of nightly build to https://github.com/CircleCI-Public/circleci-demo-php-laravel/blob/circleci-2.0/.circleci/config.yml so fellas can easily find it and copy-paste to their projects?

Thanks in advance!

**Comment by ryanwohara** [comment]
I don't want to run this project nightly. The documentation you linked is 100% accurate and you truncated the snippet you'd need.

```
workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
    jobs:
      - build
```
